name: Publish to WinGet
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: SnailDOS.SnailFM
          max-versions-to-keep: 5
          token: ${{ secrets.WINGET_TOKEN }}
